//
//  FactoryProgramFixtureTests.swift
//
//  X2-9 (ADR-080): the JUCE plugin offers a host the same 695 programs as this product's AUv3
//  offers factory presets — same order, same names — so "program 412" is one sound in both. This
//  writes what the AUv3 offers, from `S1FactoryPresets` itself; Tests/Plugin/PluginPresetTests
//  reads it on every OS. In the normal suite it CHECKS the committed file and fails when stale.
//
//      Scripts/write-factory-program-fixtures.sh
//

import XCTest
@testable import SynthOneCore
import S1Support

final class FactoryProgramFixtureTests: XCTestCase {

    private var repositoryRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }
    private var fixtureURL: URL { repositoryRoot.appendingPathComponent("Tests/Plugin/Fixtures/factory-programs.txt") }
    private var isWriting: Bool { ProcessInfo.processInfo.environment["SYNTHONE_WRITE_FACTORY_PROGRAM_FIXTURES"] == "1" }

    private func fixtureText() throws -> String {
        let unit = try S1AudioUnit(componentDescription: AKSynthOne.ComponentDescription, options: [])
        let source = S1FactoryPresets.install(into: unit)
        let names = source.factoryPresetNames()
        XCTAssertEqual(names.count, 695)
        var lines = ["# Generated by FactoryProgramFixtureTests from S1FactoryPresets. Do not edit; run Scripts/write-factory-program-fixtures.sh.",
                     "# index<TAB>name — the AUv3's factory preset numbers, which a host stores. Lines are only ever added at the end."]
        for (index, name) in names.enumerated() {
            XCTAssertFalse(name.contains("\t") || name.contains("\n"), name)
            lines.append("\(index)\t\(name)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    func testThePluginFixtureIsWhatTheAudioUnitOffers() throws {
        let fixture = try fixtureText()
        if isWriting {
            try fixture.write(to: fixtureURL, atomically: true, encoding: .utf8)
            print("SYNTHONE_WRITE_FACTORY_PROGRAM_FIXTURES: wrote \(fixtureURL.path)")
            return
        }
        let onDisk = try String(contentsOf: fixtureURL, encoding: .utf8)
        XCTAssertEqual(onDisk, fixture, "Tests/Plugin/Fixtures/factory-programs.txt is stale: run Scripts/write-factory-program-fixtures.sh")
    }
}
