//
//  LayoutSpecFixtureTests.swift
//
//  X3-1 (ADR-083): the JUCE interface is drawn from a layout specification, and the specification
//  is MEASURED, not typed — this builds the desktop layout at its design size under each skin,
//  exactly as `DesktopLayoutTests` and `SkinTests` do, and writes down where every section,
//  control, button and label landed, which parameter each control is bound to (the conductor's
//  own bindings), the fonts, and both palettes with every colour. Cabinet's rectangle table is
//  taken as it is. `Sources/S1Plugin` links the file in and `Tests/Plugin/PluginLayoutSpecTests`
//  reads it on every OS. In the normal suite this CHECKS the committed file and fails when stale.
//
//      Scripts/write-layout-spec.sh
//
//  Not in the specification, on purpose: the Cabinet extras (`docs/private/cabinet-extras.md`;
//  X3-6 scopes them), the preset browser and the sheets (X3-4, X3-5), the classic layout.
//

import XCTest
import UIKit
@testable import SynthOneCore

final class LayoutSpecFixtureTests: XCTestCase {

    private static let started: Bool = {
        SynthOneApp.start(mode: .offline)
        return true
    }()

    override func setUp() {
        super.setUp()
        _ = Self.started
    }

    override func tearDown() {
        S1Skins.current = S1StudioSkin()
        super.tearDown()
    }

    private var repositoryRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }
    private var fixtureURL: URL { repositoryRoot.appendingPathComponent("Sources/S1Plugin/Layout/layout-spec.json") }
    private var isWriting: Bool { ProcessInfo.processInfo.environment["SYNTHONE_WRITE_LAYOUT_SPEC"] == "1" }

    func testTheLayoutSpecificationIsWhatTheDesktopLayoutMeasures() throws {
        let text = try specText()
        if isWriting {
            try FileManager.default.createDirectory(at: fixtureURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            try text.write(to: fixtureURL, atomically: true, encoding: .utf8)
            print("SYNTHONE_WRITE_LAYOUT_SPEC: wrote \(fixtureURL.path)")
            return
        }
        let onDisk = try String(contentsOf: fixtureURL, encoding: .utf8)
        XCTAssertEqual(onDisk, text, "Sources/S1Plugin/Layout/layout-spec.json is stale: run Scripts/write-layout-spec.sh")
    }

    // MARK: - The document

    private func specText() throws -> String {
        let names = try parameterNames()
        var skins: [(String, JSON)] = []
        for choice in S1SkinChoice.allCases {
            skins.append((choice.rawValue, try skinSpec(choice, names: names)))
        }
        let theme = S1DesktopTheme.self
        let document = JSON.object([
            ("about", .string("GENERATED by Tests/SynthOneTests/LayoutSpecFixtureTests.swift from the Mac desktop layout. "
                              + "Do not edit; run Scripts/write-layout-spec.sh. Frames are [x, y, width, height] in points, "
                              + "origin top-left, in the window at designSize. X3-1, ADR-083.")),
            ("version", .number(1)),
            ("designSize", size(theme.designSize)),
            ("minimumSize", size(theme.minimumWindowSize)),
            ("metrics", .object([
                ("toolbarHeight", .number(theme.toolbarHeight)),
                ("playBarHeight", .number(theme.playBarHeight)),
                ("statusBarHeight", .number(theme.statusBarHeight)),
                ("sectionHeaderHeight", .number(theme.sectionHeaderHeight)),
                ("sectionCornerRadius", .number(theme.sectionCornerRadius)),
                ("editorPadding", .number(theme.editorPadding)),
                ("rowGap", .number(theme.rowGap)),
                ("trafficLightAllowance", .number(theme.trafficLightAllowance)),
                ("presetPanelWidth", .number(theme.presetPanelWidth)),
                ("presetPanelHeight", .number(theme.presetPanelHeight))
            ])),
            ("fonts", fontRoles()),
            ("skins", .object(skins))
        ])
        return document.text() + "\n"
    }

    /// The type, by role. The names are what `S1DesktopTheme.font` resolves to on the Mac; the
    /// measured labels below carry their own font, and these say which role is which.
    private func fontRoles() -> JSON {
        func role(_ size: CGFloat, _ weight: S1DesktopTheme.Weight, kern: CGFloat = 0, uppercase: Bool = false) -> JSON {
            let font = S1DesktopTheme.font(size, weight: weight)
            return .object([("name", .string(font.fontName)), ("family", .string(font.familyName)),
                            ("size", .number(size)), ("kern", .number(kern)), ("uppercase", .bool(uppercase))])
        }
        return .object([
            ("sectionTitle", role(12, .demiBold, kern: 1.2, uppercase: true)),
            ("controlTitle", role(12, .regular)),
            ("controlValue", role(11, .regular)),
            ("caption", role(11, .regular)),
            ("button", role(12, .medium)),
            ("presetName", role(15, .medium)),
            ("hint", role(11, .regular))
        ])
    }

    // MARK: - One skin

    private func skinSpec(_ choice: S1SkinChoice, names: [Int32: String]) throws -> JSON {
        let skin = choice.makeSkin()
        S1Skins.current = skin
        let manager = try XCTUnwrap(SynthOneApp.makeRootViewController(layout: .desktop) as? Manager)
        manager.view.frame = CGRect(origin: .zero, size: SynthOneApp.desktopWindowSize)
        manager.view.setNeedsLayout()
        manager.view.layoutIfNeeded()
        let layout = try XCTUnwrap(manager.desktopLayout)
        XCTAssertEqual(SynthOneApp.desktopWindowSize, S1DesktopTheme.designSize)
        let root = layout.root

        func frame(_ view: UIView) -> CGRect { view.convert(view.bounds, to: root) }
        func isShown(_ view: UIView) -> Bool {
            var current: UIView? = view
            while let v = current, v !== root {
                if v.isHidden || v.alpha == 0 { return false }
                current = v.superview
            }
            return current === root && view.bounds.width > 0 && view.bounds.height > 0
        }
        func sectionKey(of view: UIView) -> String? {
            var current: UIView? = view
            while let v = current {
                if let section = v as? S1SectionView { return layout.sections.first { $0.value === section }?.key }
                if v === layout.toolbar { return "toolbar" }
                if v === layout.playBar { return "playBar" }
                if v === layout.statusBar { return "statusBar" }
                current = v.superview
            }
            return nil
        }

        // Sections, in reading order
        let orderedSections = layout.sections.filter { isShown($0.value) }.sorted {
            let a = frame($0.value), b = frame($1.value)
            return abs(a.minY - b.minY) > 40 ? a.minY < b.minY : a.minX < b.minX
        }
        let sectionOrder = Dictionary(uniqueKeysWithValues: orderedSections.enumerated().map { ($1.key, $0) })
        let sections = JSON.array(orderedSections.map { key, section in
            var fields: [(String, JSON)] = [
                ("key", .string(key)),
                ("title", .string(section.titleLabel.text ?? "")),
                ("frame", rect(frame(section))),
                ("body", rect(frame(section.body)))
            ]
            if let header = section.titleLabel.superview { fields.append(("header", rect(frame(header)))) }
            fields.append(("accent", section.accent.map { .string(hex($0)) } ?? .null))
            return .object(fields)
        })

        // Controls: everything the conductor has bound that this layout shows
        var bound: [(S1Parameter, UIView)] = manager.conductor.bindings.compactMap { binding in
            guard let view = binding.1 as? UIView, view.isDescendant(of: root), isShown(view) else { return nil }
            return (binding.0, view)
        }
        // Wired by hand in their panels, so the conductor has no binding for them: the five
        // "dependent parameters" (the four tempo-syncable rates and the sequencer's step length —
        // their Mac knobs hold a 0…1 position, EffectsPanelController / SequencerPanelController),
        // and the play bar's Transpose (Manager+callbacks).
        let fx = manager.fxPanel
        let dependent: [(S1Parameter, UIView?)] = [(.lfo1Rate, fx.lfo1RateKnob), (.lfo2Rate, fx.lfo2RateKnob),
                                                   (.delayTime, fx.delayTimeKnob), (.autoPanFrequency, fx.autoPanRateKnob),
                                                   (.arpSeqTempoMultiplier, manager.sequencerPanel.arpSeqTempoMultiplier)]
        let handWired = dependent + [(.transpose, manager.transposeStepper)]
        for (parameter, control) in handWired {
            let view = try XCTUnwrap(control)
            XCTAssertFalse(bound.contains { $0.1 === view }, "bound after all: list it once")
            XCTAssertTrue(view.isDescendant(of: root) && isShown(view))
            bound.append((parameter, view))
        }
        let boundViews = bound.map { $0.1 }
        func order(_ view: UIView) -> (Int, CGFloat, CGFloat) {
            let f = frame(view)
            return (sectionKey(of: view).flatMap { sectionOrder[$0] } ?? 99, f.minY.rounded(), f.minX)
        }
        bound.sort { order($0.1) < order($1.1) }

        var controls: [JSON] = []
        var titleLabels: [UILabel] = []
        var ids: [String: Int] = [:]
        for (parameter, view) in bound {
            let name = try XCTUnwrap(names[parameter.rawValue], "S1Parameter \(parameter.rawValue) has no name in S1Parameter.h")
            let section = sectionKey(of: view)
            var id = "\(section ?? "window").\(name)"
            ids[id, default: 0] += 1
            if let count = ids[id], count > 1 { id += ".\(count)" }
            let className = String(describing: type(of: view))
            var fields: [(String, JSON)] = [
                ("id", .string(id)),
                ("parameter", .string(name)),
                ("kind", .string(kind(of: className))),
                ("class", .string(className)),
                ("section", section.map { .string($0) } ?? .null),
                ("frame", rect(frame(view)))
            ]
            if dependent.contains(where: { $0.1 === view }) { fields.append(("dependent", .bool(true))) }
            if let chip = view as? LFOToggle { fields.append(("title", .string(chip.buttonText))) }
            if let twoWay = view as? ToggleSwitch {
                fields.append(("choices", .array([.string(twoWay.desktopLabels.0), .string(twoWay.desktopLabels.1)])))
            }
            if let cell = view.superview as? S1ControlCell {
                fields.append(("title", .string(cell.titleLabel.text ?? "")))
                fields.append(("titleFrame", rect(line(of: cell.titleLabel, in: cell, frame: frame))))
                titleLabels.append(cell.titleLabel)
                if cell.valueLabel.superview != nil {
                    fields.append(("valueFrame", rect(line(of: cell.valueLabel, in: cell, frame: frame))))
                    titleLabels.append(cell.valueLabel)
                }
                fields.append(("cell", rect(frame(cell))))
            } else if let stack = view.superview as? UIStackView {
                let labels = stack.arrangedSubviews.compactMap { $0 as? UILabel }
                if labels.count == 1, stack.arrangedSubviews.count == 2 {
                    fields.append(("title", .string(labels[0].text ?? "")))
                    fields.append(("titleFrame", rect(frame(labels[0]))))
                    titleLabels.append(labels[0])
                }
            }
            controls.append(.object(fields))
        }
        // The filter-type picker stands in for the classic cycling button, which keeps the binding
        if let picker = layout.filterPicker, isShown(picker) {
            controls.append(.object([
                ("id", .string("Filter.filterType")), ("parameter", .string("filterType")),
                ("kind", .string("segmented")), ("class", .string("S1SegmentedControl")),
                ("section", .string("Filter")), ("frame", rect(frame(picker))),
                ("choices", .array(["Low", "Band", "High"].map { .string($0) }))
            ]))
        }

        // Views that show parameters without being bound through the conductor
        let envelopes = manager.envelopesPanel
        let pads = manager.touchPadPanel
        var displays: [JSON] = []
        func display(_ id: String, _ kind: String, _ view: UIView?, _ parameters: [(String, String)]) {
            guard let view, isShown(view) else { return }
            var colours: [(String, JSON)] = []
            if let plot = view as? AKADSRView {
                // Which envelope has a fill at all is the storyboard's word; a skin's accent recolours both
                colours = [("curve", .string(hex(plot.curveColor))),
                           ("fill", plot.attackColor.cgColor.alpha > 0 ? .string(hex(plot.attackColor)) : .null)]
            }
            displays.append(.object([("id", .string(id)), ("kind", .string(kind))] + colours + [
                ("section", sectionKey(of: view).map { .string($0) } ?? .null),
                ("frame", rect(frame(view))),
                ("parameters", .object(parameters.map { ($0.0, .string($0.1)) }))
            ]))
        }
        display("Filter Envelope.plot", "adsr", envelopes.filterADSRView,
                [("attack", "filterAttackDuration"), ("decay", "filterDecayDuration"),
                 ("sustain", "filterSustainLevel"), ("release", "filterReleaseDuration")])
        display("Amplitude Envelope.plot", "adsr", envelopes.adsrView,
                [("attack", "attackDuration"), ("decay", "decayDuration"),
                 ("sustain", "sustainLevel"), ("release", "releaseDuration")])
        display("Pads.pad1", "xyPad", pads.touchPad1, [("x", "lfo1Rate"), ("y", "lfo1Amplitude")])
        display("Pads.pad2", "xyPad", pads.touchPad2, [("x", "cutoff"), ("y", "resonance")])
        for entry in displays {
            if case .object(let fields) = entry, case .object(let parameters)? = fields.first(where: { $0.0 == "parameters" })?.1 {
                for case (_, .string(let name)) in parameters {
                    XCTAssertTrue(names.values.contains(name), "\(name) is not an S1Parameter")
                }
            }
        }

        // Everything else a person can see or press: named views first, then every button
        var items: [JSON] = []
        var itemViews: [UIView] = []
        func item(_ id: String, _ kind: String, _ view: UIView?, title: String? = nil) {
            guard let view, isShown(view), !itemViews.contains(where: { $0 === view }) else { return }
            itemViews.append(view)
            var fields: [(String, JSON)] = [("id", .string(id)), ("kind", .string(kind)),
                                            ("region", sectionKey(of: view).map { .string($0) } ?? .null),
                                            ("frame", rect(frame(view)))]
            if let title { fields.append(("title", .string(title))) }
            items.append(.object(fields))
        }
        item("wordmark", "image", layout.wordmark)
        item("presetField", "presetField", layout.presetField)
        item("presetName", "text", layout.header?.displayLabel)
        if let navigator = layout.presetField.superview as? UIStackView, navigator.arrangedSubviews.count == 3 {
            // Studio's chevrons are images with no title; Cabinet's painted ones are found by name below
            item("button.Previous preset", "button", navigator.arrangedSubviews[0], title: "Previous preset")
            item("button.Next preset", "button", navigator.arrangedSubviews[2], title: "Next preset")
        }
        item("dice", "button", layout.header?.diceButton, title: "Randomize")
        item("scope", "scope", manager.conductor.audioPlotter)
        item("record", "button", manager.generatorsPanel.recordButton, title: "Record")
        item("recordStatus", "text", manager.generatorsPanel.recordStatus)
        item("octave", "stepper", manager.octaveStepper, title: "Octave")
        item("tuning", "button", layout.tuningButton, title: "Tuning")

        var buttonCount: [String: Int] = [:]
        var queue: [UIView] = [root]
        var labels: [UILabel] = []
        while !queue.isEmpty {
            let view = queue.removeFirst()
            if view === layout.presetPanel || !isShown(view) && view !== root { continue }
            if isCabinetExtra(view) { continue }
            if boundViews.contains(where: { $0 === view }) || view === layout.filterPicker { continue }
            if itemViews.contains(where: { $0 === view }) && !(view === layout.presetField) { continue }
            if let button = view as? UIButton {
                let title = button.currentTitle ?? button.currentAttributedTitle?.string ?? button.accessibilityLabel ?? ""
                if !title.isEmpty, frame(button).width < 400 {   // not the full-window click catchers
                    var id = "button." + title
                    buttonCount[id, default: 0] += 1
                    if let count = buttonCount[id], count > 1 { id += ".\(count)" }
                    item(id, "button", button, title: title)
                }
                continue
            }
            if let label = view as? UILabel, !(label.text ?? "").isEmpty, label.alpha > 0,
               !titleLabels.contains(where: { $0 === label }) {
                labels.append(label)
                continue
            }
            queue.append(contentsOf: view.subviews)
        }
        let stateful: [UILabel?] = [layout.header?.displayLabel, manager.generatorsPanel.recordStatus]
        let labelSpecs = labels.filter { label in !stateful.contains { $0 === label } }
            .sorted { (frame($0).minY.rounded(), frame($0).minX) < (frame($1).minY.rounded(), frame($1).minX) }
            .map { label -> JSON in
                .object([
                    ("text", .string(label.text ?? "")),
                    ("region", sectionKey(of: label).map { .string($0) } ?? .null),
                    ("frame", rect(frame(label))),
                    ("font", .string(label.font.fontName)),
                    ("size", .number(label.font.pointSize)),
                    ("colour", .string(hex(label.textColor))),
                    ("align", .string(label.textAlignment == .center ? "centre" : label.textAlignment == .right ? "right" : "left"))
                ])
            }

        let knobSizes = Set(bound.compactMap { $0.1 is Knob ? Double(frame($0.1).width) : nil }).sorted()
        let rows = layout.editor.arrangedSubviews.map { JSON.number(frame($0).height) }

        var fields: [(String, JSON)] = [
            ("title", .string(choice.title)),
            ("isDefault", .bool(choice == S1SkinChoice.default)),
            ("glow", .number(skin.glow)),
            ("palette", mirror(skin.palette)),
            ("dress", mirror(skin.dress)),
            ("frameAccent", skin.frameAccent.map { .string(hex($0)) } ?? .null),
            ("sectionGlow", skin.sectionGlow.map { .string(hex($0)) } ?? .null)
        ]
        if let template = skin.template {
            fields.append(("template", templateSpec(template)))
        } else {
            fields.append(("template", .null))
            fields.append(("rowHeights", .array(rows)))
        }
        fields += [
            ("knobSizes", .array(knobSizes.map { .number($0) })),
            ("regions", .object([
                ("toolbar", layout.toolbar.isHidden ? .null : rect(frame(layout.toolbar))),
                ("editor", layout.editor.isHidden ? .null : rect(frame(layout.editor))),
                ("playBar", rect(frame(layout.playBar))),
                ("statusBar", rect(frame(layout.statusBar)))
            ])),
            ("sections", sections),
            ("controls", .array(controls)),
            ("displays", .array(displays)),
            ("items", .array(items)),
            ("labels", .array(labelSpecs))
        ]
        return .object(fields)
    }

    /// A cell's title or readout, as the full width of its cell: the text is centred in it, and
    /// its own width changes with what it says.
    private func line(of label: UILabel, in cell: UIView, frame: (UIView) -> CGRect) -> CGRect {
        let own = frame(label), whole = frame(cell)
        return CGRect(x: whole.minX, y: own.minY, width: whole.width, height: own.height)
    }

    /// `docs/private/cabinet-extras.md`: not in the specification. X3-6 scopes them.
    private func isCabinetExtra(_ view: UIView) -> Bool {
        if view is S1CabinetJoystick { return true }
        if let button = view as? UIButton, let label = button.accessibilityLabel {
            return label == NSLocalizedString("Cut the power", comment: "") || label == NSLocalizedString("Restore the power", comment: "")
        }
        return false
    }

    /// The painting's rectangle table, as `S1CabinetSkin` has it: the painting's own pixels.
    private func templateSpec(_ template: S1SkinTemplate) -> JSON {
        func corners(_ r: CGRect) -> JSON { rect(r) }
        return .object([
            ("about", .string("Rectangles are [x, y, width, height] in the painting's pixels; the layout places each as a fraction of `size`.")),
            ("image", .string(template.imageName)),
            ("size", size(template.size)),
            ("sections", .object(template.sections.sorted { $0.key < $1.key }.map { ($0.key, corners($0.value)) })),
            ("presetField", corners(template.presetField)),
            ("previous", corners(template.previous)),
            ("next", corners(template.next)),
            ("dice", .array([.number(template.dice.x), .number(template.dice.y)])),
            ("wordmark", corners(template.wordmark)),
            ("scope", corners(template.scope)),
            ("save", corners(template.save)),
            ("record", corners(template.record)),
            ("panic", corners(template.panic)),
            ("settings", corners(template.settings)),
            ("presets", corners(template.presets)),
            ("playBar", corners(template.playBar)),
            ("statusBar", corners(template.statusBar)),
            // X3-6: the cabinet's stick. The painting has it cut out (generate.py lifts it and
            // fills the hole), so a window that does not draw these two sprites shows an empty
            // console. Measured here, never typed into C++.
            ("joystick", template.joystick.map { stick in
                JSON.object([
                    ("ballImage", .string(stick.ballImageName)),
                    ("ballBox", corners(stick.ballBox)),
                    ("rodImage", .string(stick.rodImageName)),
                    ("rodBox", corners(stick.rodBox)),
                    ("pivot", .array([.number(stick.pivot.x), .number(stick.pivot.y)])),
                    ("reach", corners(stick.reach))
                ])
            } ?? .null),
            // X3-9: the two red buttons that cut and restore the power (ADR-062), the zones they
            // darken, the grey painting, and how far a section's frame and glow reach past its
            // inner edge. Measured here from `S1CabinetSkin`, never typed into C++.
            ("power", template.power.map { power in
                JSON.object([
                    ("darkImage", .string(power.darkImageName)),
                    ("off", corners(power.off)),
                    ("on", corners(power.on)),
                    ("frameReach", .number(power.frameReach)),
                    ("zones", .object(power.zones.sorted { $0.key < $1.key }.map { ($0.key, corners($0.value)) }))
                ])
            } ?? .null)
        ])
    }

    /// What the controls kit (X3-2) calls each Mac class.
    private func kind(of className: String) -> String {
        switch className {
        case "Knob", "MIDIKnob": return "knob"
        case "ToggleButton", "MIDIToggleButton", "FlatToggleButton": return "switch"
        case "ToggleSwitch", "MIDIToggleSwitch": return "twoWay"
        case "LFOToggle": return "chip"
        case "LFOWavePicker": return "wavePicker"
        case "MorphSelector": return "morphSelector"
        case "Stepper", "MIDIStepper": return "stepper"
        case "TempoStepper": return "tempo"
        case "ArpDirectionButton", "MIDIArpDirectionButton": return "direction"
        case "SliderTransposeButton": return "stepOctave"
        case "VerticalSlider": return "stepFader"
        case "ArpButton": return "stepOn"
        default: return "other"
        }
    }

    // MARK: - S1Parameter's names, as CMake reads them (Sources/S1Plugin/CMakeLists.txt)

    private func parameterNames() throws -> [Int32: String] {
        let header = try String(contentsOf: repositoryRoot.appendingPathComponent("Sources/S1Engine/S1Parameter.h"), encoding: .utf8)
        let pattern = try NSRegularExpression(pattern: "^ +([A-Za-z][A-Za-z0-9_]*) = ([0-9]+),?", options: [.anchorsMatchLines])
        var names: [Int32: String] = [:]
        for match in pattern.matches(in: header, range: NSRange(header.startIndex..., in: header)) {
            guard let name = Range(match.range(at: 1), in: header), let number = Range(match.range(at: 2), in: header),
                  let index = Int32(header[number]) else { continue }
            if String(header[name]) == "S1ParameterCount" { continue }
            names[index] = String(header[name])
        }
        XCTAssertEqual(names.count, 150)
        return names
    }

    // MARK: - Values

    private func rect(_ r: CGRect) -> JSON {
        .array([.number(r.minX), .number(r.minY), .number(r.width), .number(r.height)])
    }

    private func size(_ s: CGSize) -> JSON { .array([.number(s.width), .number(s.height)]) }

    private func hex(_ colour: UIColor) -> String {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        colour.getRed(&r, green: &g, blue: &b, alpha: &a)
        func byte(_ v: CGFloat) -> Int { Int((max(0, min(1, v)) * 255).rounded()) }
        return String(format: "#%02x%02x%02x%02x", byte(r), byte(g), byte(b), byte(a))
    }

    /// Every stored property of a palette or a dress, by its own name, so a new one cannot be forgotten.
    private func mirror(_ value: Any) -> JSON {
        .object(Mirror(reflecting: value).children.compactMap { child in
            guard let label = child.label else { return nil }
            return (label, json(child.value))
        })
    }

    private func json(_ value: Any) -> JSON {
        let mirrored = Mirror(reflecting: value)
        if mirrored.displayStyle == .optional {
            guard let some = mirrored.children.first else { return .null }
            return json(some.value)
        }
        switch value {
        case let colour as UIColor: return .string(hex(colour))
        case let colours as [UIColor]: return .array(colours.map { .string(hex($0)) })
        case let flag as Bool: return .bool(flag)
        case let number as CGFloat: return .number(number)
        case let number as Float: return .number(CGFloat(number))
        case let number as Double: return .number(CGFloat(number))
        case let s as CGSize: return size(s)
        default:
            XCTFail("LayoutSpecFixtureTests cannot write a \(type(of: value))")
            return .null
        }
    }
}

// MARK: - A small JSON writer: keys in the order given, numbers to a hundredth of a point

private indirect enum JSON {
    case object([(String, JSON)])
    case array([JSON])
    case string(String)
    case number(CGFloat)
    case bool(Bool)
    case null

    private var isFlat: Bool {
        switch self {
        case .object: return false
        case .array(let items): return items.allSatisfy { if case .object = $0 { return false }; if case .array = $0 { return false }; return true }
        default: return true
        }
    }

    /// Objects one field per line — except an object of scalars and flat arrays, which is one
    /// line, so a control is one line of the file and a diff reads control by control.
    func text(indent: Int = 0) -> String {
        let pad = String(repeating: "  ", count: indent)
        switch self {
        case .null: return "null"
        case .bool(let flag): return flag ? "true" : "false"
        case .number(let number):
            let rounded = (Double(number) * 100).rounded() / 100
            if rounded == rounded.rounded() { return String(Int(rounded)) }
            var text = String(format: "%.2f", rounded)
            while text.hasSuffix("0") { text.removeLast() }
            return text
        case .string(let string):
            var out = "\""
            for scalar in string.unicodeScalars {
                switch scalar {
                case "\"": out += "\\\""
                case "\\": out += "\\\\"
                case "\n": out += "\\n"
                case "\t": out += "\\t"
                default:
                    if scalar.value < 0x20 { out += String(format: "\\u%04x", scalar.value) } else { out.unicodeScalars.append(scalar) }
                }
            }
            return out + "\""
        case .array(let items):
            if items.isEmpty { return "[]" }
            if isFlat { return "[" + items.map { $0.text() }.joined(separator: ", ") + "]" }
            return "[\n" + items.map { pad + "  " + $0.text(indent: indent + 1) }.joined(separator: ",\n") + "\n" + pad + "]"
        case .object(let fields):
            if fields.isEmpty { return "{}" }
            if fields.allSatisfy({ $0.1.isFlat }) && indent >= 3 {
                return "{" + fields.map { JSON.string($0.0).text() + ": " + $0.1.text() }.joined(separator: ", ") + "}"
            }
            return "{\n" + fields.map { pad + "  " + JSON.string($0.0).text() + ": " + $0.1.text(indent: indent + 1) }.joined(separator: ",\n") + "\n" + pad + "}"
        }
    }
}
