//
//  PresetFixtureTests.swift
//  SynthOneTests
//
//  X1-5 (ADR-069). The Swift preset code is the reference; the engine carries a C++ transcription
//  (Sources/S1Engine/Presets/S1Preset). This test writes what the Swift does with every factory
//  preset — the decoded fields and the 150 parameter values after `apply` — to
//  Tests/Engine/Fixtures/factory-presets.txt, which the CMake test PresetTests checks the C++
//  against. Write mode: SYNTHONE_WRITE_PRESET_FIXTURES=1 (Scripts/write-preset-fixtures.sh).
//  Check mode (the normal suite): the fixture on disk must equal what the Swift produces now.
//
//  Presets are applied to one synth in bank order, as the C++ test applies them, so the two
//  see the same dependent-parameter history.
//

import XCTest
@testable import SynthOneCore
import S1Support

final class PresetFixtureTests: XCTestCase {

    private var repositoryRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }
    private var fixtureURL: URL { repositoryRoot.appendingPathComponent("Tests/Engine/Fixtures/factory-presets.txt") }
    private var isWriting: Bool { ProcessInfo.processInfo.environment["SYNTHONE_WRITE_PRESET_FIXTURES"] == "1" }

    private func g17(_ x: Double) -> String { String(format: "%.17g", x) }
    private func escaped(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\t", with: "\\t")
            .replacingOccurrences(of: "\n", with: "\\n").replacingOccurrences(of: "\r", with: "\\r")
    }

    private func fixtureText() throws -> String {
        let rig = try OfflineSynth()
        let synth = rig.synth
        let defaults = synth.presetDefaults
        var lines = ["# Generated by PresetFixtureTests from the Swift preset code. Do not edit; run Scripts/write-preset-fixtures.sh.",
                     "banks\t" + S1FactoryPresets.bankOrder.joined(separator: "\t")]
        var total = 0
        for bank in S1FactoryPresets.bankOrder {
            let url = try XCTUnwrap(Bundle.synthOneCore.url(forResource: bank, withExtension: "json"))
            let json = try JSONSerialization.jsonObject(with: Data(contentsOf: url))
            let array = try XCTUnwrap(json as? [Any])
            let presets = Preset.parseDataToPresets(jsonArray: array, defaults: defaults)
            for (index, preset) in presets.enumerated() {
                preset.apply(to: synth)
                let values = (0..<Int(S1Parameter.S1ParameterCount.rawValue)).map { i -> String in
                    g17(synth.getSynthParameter(S1Parameter(rawValue: Int32(i))!))
                }
                let tuningName: String = preset.tuningName.map(escaped) ?? "-"
                let masterSet: String = preset.tuningMasterSet.map { $0.map(g17).joined(separator: " ") } ?? "-"
                let pattern: String = preset.seqPatternNote.map { String($0) }.joined(separator: " ")
                let boost: String = preset.seqOctBoost.map { $0 ? "1" : "0" }.joined(separator: " ")
                let noteOn: String = preset.seqNoteOn.map { $0 ? "1" : "0" }.joined(separator: " ")
                var fields: [String] = ["preset", bank, String(index), escaped(preset.name), preset.uid, tuningName, masterSet]
                fields += [pattern, boost, noteOn, preset.isUser ? "1" : "0", preset.isFavorite ? "1" : "0"]
                fields += [String(preset.category), String(preset.octavePosition), String(preset.position)]
                fields += [escaped(preset.author), escaped(preset.userText), values.joined(separator: " ")]
                lines.append(fields.joined(separator: "\t"))
                total += 1
            }
        }
        XCTAssertEqual(total, 695, "the factory banks hold 695 presets")

        // The keys JSONEncoder writes, so the C++ writer can be held to the same set: without a
        // tuning (nil optionals are omitted) and with one.
        let encoder = JSONEncoder()
        func keys(of preset: Preset) throws -> [String] {
            let data = try encoder.encode(preset)
            let object = try XCTUnwrap(try JSONSerialization.jsonObject(with: data) as? [String: Any])
            return object.keys.sorted()
        }
        let plain = Preset()
        lines.append("keys\t" + (try keys(of: plain)).joined(separator: " "))
        let tuned = Preset()
        tuned.tuningName = "Wilson Hexany(1, 3, 5, 7)"
        tuned.tuningMasterSet = [1, 3, 5, 7]
        lines.append("keysWithTuning\t" + (try keys(of: tuned)).joined(separator: " "))
        return lines.joined(separator: "\n") + "\n"
    }

    func testTheEngineFixtureMatchesTheSwiftPresetCode() throws {
        let fixture = try fixtureText()
        if isWriting {
            try fixture.write(to: fixtureURL, atomically: true, encoding: .utf8)
            print("SYNTHONE_WRITE_PRESET_FIXTURES: wrote \(fixtureURL.path)")
            return
        }
        let onDisk = try String(contentsOf: fixtureURL, encoding: .utf8)
        XCTAssertEqual(onDisk, fixture, "Tests/Engine/Fixtures/factory-presets.txt is stale: run Scripts/write-preset-fixtures.sh")
    }
}
