//
//  TuningFixtureTests.swift
//  SynthOneTests
//
//  X1-4 (ADR-068). The Swift tuning code is the reference; the portable engine carries a C++ port
//  of the table and the Scala parser, and the factory tunings as generated data. This test keeps
//  the two in step:
//
//    check mode (default)  — regenerates both files in memory and fails if either differs from
//                            what is on disk, so a change to the Swift list or the table code
//                            cannot go unnoticed by the engine.
//    write mode            — SYNTHONE_WRITE_TUNING_FIXTURES=1 (Scripts/write-tuning-fixtures.sh)
//                            writes Tests/Engine/Fixtures/factory-tunings.txt, which the CMake
//                            test TuningTableTests reads, and Sources/S1Engine/Tunings/
//                            S1FactoryTunings.cpp, the engine's copy of the factory list.
//
//  Numbers are printed with %.17g so a double round-trips exactly.
//

import XCTest
@testable import SynthOneCore
import S1Support

final class TuningFixtureTests: XCTestCase {

    private var repositoryRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }
    private var fixtureURL: URL { repositoryRoot.appendingPathComponent("Tests/Engine/Fixtures/factory-tunings.txt") }
    private var generatedURL: URL { repositoryRoot.appendingPathComponent("Sources/S1Engine/Tunings/S1FactoryTunings.cpp") }
    private var isWriting: Bool { ProcessInfo.processInfo.environment["SYNTHONE_WRITE_TUNING_FIXTURES"] == "1" }

    private func g17(_ x: Double) -> String { String(format: "%.17g", x) }

    /// The Scala inputs the C++ parser is checked against: the common shapes, and the quirks.
    static let scalaCases: [String] = [
        // cents, the usual .scl
        "! twelve.scl\n!\n12 tone equal temperament\n 12\n!\n 100.0\n 200.0\n 300.0\n 400.0\n 500.0\n 600.0\n 700.0\n 800.0\n 900.0\n 1000.0\n 1100.0\n 2/1\n",
        // ratios and whole numbers, CRLF line endings, a comment among the degrees
        "! ratios.scl\r\nJust intonation, five limit\r\n 7\r\n 9/8\r\n 5/4\r\n! a comment\r\n 4/3\r\n 3/2\r\n 5/3\r\n 15/8\r\n 3\r\n",
        // 1/1 and 2 are skipped; a cents line with trailing text is skipped, not parsed (the Swift parses the whole line)
        "! quirks.scl\nquirks\n 4\n 1/1\n 386.3137 major third\n 702.0\n 2\n",
        // a bad ratio: the whole file is rejected
        "! bad.scl\nbad\n 2\n 3/0\n 3/2\n",
        // a count of 0 is rejected (the spec allows it; AudioKit's parser does not)
        "! empty.scl\nempty\n 0\n",
        // negative cents are folded to positive; leading '.' forms parse
        "! forms.scl\nforms\n 3\n -100.\n .5\n 1200.0\n",
    ]

    private func escaped(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    private struct Entry { let bank: String; let name: String; let masterSet: [Double] }

    private func entries() -> [Entry] {
        Tunings.defaultTunings().map { Entry(bank: "Curated", name: $0.0, masterSet: $0.1()) }
            + Tunings.hexanyTriadTunings().map { Entry(bank: Tunings.hexanyTriadTuningsBankName, name: $0.0, masterSet: $0.1()) }
    }

    private func fixtureText() -> String {
        var lines = ["# Generated by TuningFixtureTests from the Swift tuning code. Do not edit; run Scripts/write-tuning-fixtures.sh.",
                     "nyquist\t\(g17(AKTuningTableBase.NYQUIST))"]
        for entry in entries() {
            let table = AKTuningTable()
            let npo = table.tuningTable(fromFrequencies: entry.masterSet)
            let frequencies = (0..<AKTuningTable.midiNoteCount).map { table.frequency(forNoteNumber: MIDINoteNumber($0)) }
            lines.append(["tuning", entry.bank, entry.name, "\(npo)",
                          entry.masterSet.map(g17).joined(separator: " "),
                          frequencies.map(g17).joined(separator: " ")].joined(separator: "\t"))
        }
        for text in Self.scalaCases {
            let parsed = AKTuningTable().frequencies2(fromScalaString: text)
            lines.append(["scala", escaped(text), parsed.map { $0.map(g17).joined(separator: " ") } ?? "nil"].joined(separator: "\t"))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private func generatedSource() -> String {
        func cString(_ s: String) -> String {
            "\"" + s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
        }
        var out = """
        // GENERATED by TuningFixtureTests (Tests/SynthOneTests/TuningFixtureTests.swift) from
        // Sources/SynthOneCore/Tunings/Model/Tunings+DefaultTunings.swift. DO NOT EDIT: change the Swift
        // and run Scripts/write-tuning-fixtures.sh. The check-mode test fails if this file is stale.
        #include "S1FactoryTunings.hpp"

        namespace s1 {

        const char *const kBundleTuningsBankName = "Curated";
        const char *const kHexanyTriadTuningsBankName = \(cString(Tunings.hexanyTriadTuningsBankName));

        const std::vector<FactoryTuning> &factoryTunings() {
            static const std::vector<FactoryTuning> tunings = {

        """
        for entry in entries() {
            let bank = entry.bank == "Curated" ? "kBundleTuningsBankName" : "kHexanyTriadTuningsBankName"
            out += "        {\(bank), \(cString(entry.name)), {\(entry.masterSet.map(g17).joined(separator: ", "))}},\n"
        }
        out += """
            };
            return tunings;
        }

        }  // namespace s1

        """
        return out
    }

    func testTheEngineFixturesMatchTheSwiftTuningCode() throws {
        let fixture = fixtureText()
        let source = generatedSource()
        XCTAssertGreaterThan(entries().count, 190, "the factory list is shorter than it was")

        if isWriting {
            try FileManager.default.createDirectory(at: fixtureURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            try fixture.write(to: fixtureURL, atomically: true, encoding: .utf8)
            try source.write(to: generatedURL, atomically: true, encoding: .utf8)
            print("SYNTHONE_WRITE_TUNING_FIXTURES: wrote \(fixtureURL.path) and \(generatedURL.path)")
            return
        }
        let onDiskFixture = try String(contentsOf: fixtureURL, encoding: .utf8)
        let onDiskSource = try String(contentsOf: generatedURL, encoding: .utf8)
        XCTAssertEqual(onDiskFixture, fixture, "Tests/Engine/Fixtures/factory-tunings.txt is stale: run Scripts/write-tuning-fixtures.sh")
        XCTAssertEqual(onDiskSource, source, "Sources/S1Engine/Tunings/S1FactoryTunings.cpp is stale: run Scripts/write-tuning-fixtures.sh")
    }
}
