//  X1-6 (ADR-070): the Swift wavetable loader writes down what it loads, and the C++ loader in
//  Sources/S1Engine/Wavetables has to load the same floats (Tests/Engine/WavetableTests.cpp).
//
//  Two modes, as the tuning and preset fixtures have:
//    write  SYNTHONE_WRITE_WAVETABLE_FIXTURES=1 (Scripts/write-wavetable-fixtures.sh) rewrites
//           Tests/Engine/Fixtures/wavetables.txt
//    check  the normal suite: the file on disk must equal what the Swift loads today
//
//  213,005 floats as text would be megabytes, so a table is its size, an FNV-1a 64 of its
//  samples' bit patterns (little-endian bytes), and its first eight samples in hex for a reader.
//  The 13 band frequencies are written whole.

import XCTest
@testable import SynthOneCore
import S1Support

final class WavetableFixtureTests: XCTestCase {

    private var repositoryRoot: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
    }
    private var fixtureURL: URL { repositoryRoot.appendingPathComponent("Tests/Engine/Fixtures/wavetables.txt") }
    private var isWriting: Bool { ProcessInfo.processInfo.environment["SYNTHONE_WRITE_WAVETABLE_FIXTURES"] == "1" }

    private func hex(_ value: Float) -> String { String(format: "%08x", value.bitPattern) }

    private func fnv1a64(_ samples: [Float]) -> UInt64 {
        var hash: UInt64 = 0xcbf2_9ce4_8422_2325
        for sample in samples {
            var bits = sample.bitPattern
            for _ in 0..<4 {
                hash ^= UInt64(bits & 0xff)
                hash = hash &* 0x0000_0100_0000_01b3
                bits >>= 8
            }
        }
        return hash
    }

    private func fixtureText() throws -> String {
        let tables = try S1Wavetables.load()
        let nameData = try Data(contentsOf: XCTUnwrap(Bundle.synthOneCore.url(forResource: "bandlimitedWaveforms", withExtension: "json")))
        let names = try JSONDecoder().decode([String].self, from: nameData)
        XCTAssertEqual(tables.waveforms.count, S1Wavetables.waveformCount * S1Wavetables.bandCount)
        XCTAssertEqual(tables.bandlimitFrequencies.count, S1Wavetables.bandCount)

        var lines = ["# Generated by WavetableFixtureTests from the Swift wavetable loader. Do not edit; run Scripts/write-wavetable-fixtures.sh.",
                     "frequencies\t" + tables.bandlimitFrequencies.map(hex).joined(separator: " ")]
        for (index, table) in tables.waveforms.enumerated() {
            let samples = Array(table)
            XCTAssertEqual(samples.count, S1Wavetables.tableSize, names[index])
            let first: String = samples.prefix(8).map(hex).joined(separator: " ")
            let fields: [String] = ["table", String(index), names[index], String(samples.count),
                                    String(format: "%016llx", fnv1a64(samples)), first]
            lines.append(fields.joined(separator: "\t"))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    func testTheEngineFixtureMatchesTheSwiftWavetableLoader() throws {
        let fixture = try fixtureText()
        if isWriting {
            try fixture.write(to: fixtureURL, atomically: true, encoding: .utf8)
            print("SYNTHONE_WRITE_WAVETABLE_FIXTURES: wrote \(fixtureURL.path)")
            return
        }
        let onDisk = try String(contentsOf: fixtureURL, encoding: .utf8)
        XCTAssertEqual(onDisk, fixture, "Tests/Engine/Fixtures/wavetables.txt is stale: run Scripts/write-wavetable-fixtures.sh")
    }
}
